#analyze data generated by IJ-macro_DV-split-norm.java 

library(dplyr)
library(ggplot2)
library(scales)
library("reshape2")

path<-"C:/Users/SHU/Documents/Doc/UltradianCycle/UC-Plots/All_Figs/Figs_D/Fig1/"
dt <- 15   # Input, interval=15min ##########################
offs <- 0  # Input offset in Hours ###########################
cnm <- c("Lum","pHrodo")  # Channel/sensor names #########################
setwd(path)
file <- 'LV_UC20210910pH15m'  #file name
files <- list.files(pattern='.csv$') %>% grep(file, ., value=T)

# # function to detrend a df by subtracting loess line then add back means of loess fit; span adjustable
# detrend <- function(x){
#   ## response
#   vars <- colnames(x)
#   ## covariate
#   id <- 1:nrow(x)
#   # define a loess filter function (fitting loess regression line) for each column of a df
#   loess.filter <- function (y, span) loess(formula = as.formula(paste(y, "id", sep = "~")),
#                                            data = data.frame(x),
#                                            degree = 1,
#                                            span = span)$fitted 
#   ## apply loess filter column-by-column
#   new.x <- as.data.frame(lapply(vars, loess.filter, span = 0.75), col.names = colnames(x))
#   bsl<-matrix(rep(colMeans(new.x),each=nrow(new.x)),nrow=nrow(new.x))
#   return(x-new.x+bsl)
# }

#read data --------
df <- lapply(cnm, function(x) {read.csv(grep(x, files, value=T)) %>% pull(Average)}) %>% 
  do.call(cbind, .) %>% as.data.frame %>% `names<-`(cnm)
df1 <- sweep(df, 2, colMeans(df), FUN="/") #normalize to mean of each column
df1$Hours <- (1:nrow(df1)-1)/(60/dt)+offs				# offset hours after Shock


#plot -----------
# setwd(path)
scaleFUN <- function(x) sprintf("%.2f", x)  # digits

# make long form data
dat0<-df1   # wide form data
n<-ncol(dat0)-1  # number of sensors
clrs<-c("blue", "red", "green", "orange","violet","cyan") # 6 colours
c<-clrs[1:n]
dat1 <- melt(dat0, id.vars="Hours", variable.name="Sensor", value.name="Intensity")
p <- ggplot(data=dat1, aes(x=Hours, y=Intensity, group = Sensor)) +  
  geom_line(linetype=1, aes(color=Sensor), size=0.25, alpha=0.75)+
  ylab("R.I.") +
  xlab("Hours") + 
  theme_classic() +       # Removes gridlines & background
  theme(axis.title = element_text(face = "plain", color = "black", size = 6), 
        axis.text = element_text(face = "plain", color = "black", size = 5), 
        axis.line = element_line(colour = "black", size = 0.1),
        axis.ticks = element_line(colour = "black", size = 0.1),
        axis.ticks.length = unit(1, "pt"),
        # panel.border = element_rect(colour = "black", fill=NA, size=0.1),
        plot.margin = margin(1, 1, 1, 1, "pt"),
        legend.position = c(0.6, 0.16),
        legend.title = element_blank(),
        legend.background = element_blank(),
        legend.text = element_text(size=5),
        legend.key.height = unit(0.01,"line"),
        legend.key.width = unit(0.2, "line"),
        legend.spacing.x = unit(0.1, "line"),
        # legend.spacing.y = unit(0.005, "line")
  )+
  guides(colour = guide_legend(nrow = 1))+
  scale_color_manual(values=c)+
  scale_y_continuous(expand=c(0.05,0.), breaks=pretty_breaks(n = 3), labels=scaleFUN) # set y-axis labels

# output pdf
ggsave(filename=paste(file,"pdf",sep="."), plot=p, useDingbats=F, width=1.25, height=.75) 



#plot 2 y axes ------------
df$Hours <- (1:nrow(df)-1)/(60/dt)+offs				# offset hours after Shock

scaleFUN <- function(x) sprintf("%.0f", x)  # digits

d.range <- diff(range(df$Lum))/diff(range(df$pHrodo))


plt <- ggplot()+
  geom_line(data=df, aes(x=Hours, y=(pHrodo-min(pHrodo))*d.range+min(Lum)), linetype=1,size=0.2, color = "red", alpha=0.75)+
  geom_line(data=df, aes(x=Hours, y=Lum), stat = "identity", linetype=1, size=0.2, color = "blue", alpha=0.75)+
  xlab("Hours") + 
  scale_y_continuous(name = "Luminescence",
                     expand = c(0.1,0.1),
                     labels=scaleFUN,
                     breaks=pretty_breaks(n = 4),
                     sec.axis = sec_axis(~(.-min(df$Lum))/d.range+min(df$pHrodo), name = "pHrodo")) +
  theme_classic() +       # Removes gridlines & background
  theme(
    axis.title.y = element_text(color = "blue"),
    axis.title.y.right = element_text(color = "red"),
    axis.title = element_text(face = "plain", color = "black", size = 5),
    axis.text = element_text(face = "plain", color = "black", size = 4), 
    axis.line = element_blank(),
    axis.ticks = element_line(colour = "black", size = 0.1),
    axis.ticks.length = unit(1, "pt"),
    plot.margin = margin(0, 0, 0, 0, "pt"),
    panel.border = element_rect(colour = "black", fill=NA, size=0.1)
  )

ggsave(filename=paste(file,"pdf",sep="_2y."), plot=plt, useDingbats=F, width=1.5, height=.75) 

